### ISSUE TITLE
Walletfy-cli

### ISSUE THREAD

**Issue by roberthgnz** [sammwyy/Walletfy#8]
I've created a cli for Walletfy, you can take a look at it
https://github.com/eliut505/Walletfy-cli

**Comment by br14n-sol** [comment]
It would be more practical if the central library provided a list of supported currencies, right? 🤔

**Comment by eliut505** [comment]
> Sería más práctico si la biblioteca central proporcionara una lista de monedas admitidas, ¿verdad? 🤔
Yes, definitely. I think it's something for @sammwyy to consider

**Comment by eliut505** [comment]
> > Yes, definitely. I think it's something for @sammwyy to consider

**Comment by roberthgnz** [comment]
#10
